### ISSUE TITLE
Feature request: method properties() and reverse() on Node

### ISSUE THREAD

**Issue by pchampin** [timothee-haudebourg/json-ld#20]
These method would produce an iterator over (`Reference`, `Indexed<Object>`) pairs, or something similar.

I am working on the JSON-LD parser for [Sophia](https://github.com/pchampin/sophia_rs), and I need to inspect the output for `expand` to produce RDF quads. I could convert it to a `JsonValue`, but that would introduce an unnecessary overhead, IMO.

Or am I missing something?

**Comment by timothee-haudebourg** [comment]
I've released version 0.5.0 which includes the two methods [`Node::properties`](https://docs.rs/json-ld/0.5.0/json_ld/object/node/struct.Node.html#method.properties) and [`reverse_properties`](https://docs.rs/json-ld/0.5.0/json_ld/object/node/struct.Node.html#method.reverse_properties) that should do what you need, along with some other useful methods. 

Beware that I also moved away from the `json` crate. The JSON type is now a type parameter. It can theoretically be any JSON type as long as it implements the `generic_json::Json` trait, but for now only the [`ijson::IValue`](https://docs.rs/ijson/0.1.3/ijson/struct.IValue.html) type does, which can be parsed using `serde_json`. I plan to add support for `serde_json::Value` [as soon as possible](https://github.com/serde-rs/json/pull/814).

**Comment by pchampin** [comment]
I tried to do the switch, but it created a subdependency on `cc-traits` 0.7.0 which needs the unstable toolchain (`#![feature(generic_associated_types)]`).

Is this dependency unavoidable?? As much as I would love to use GATs myself, I prefer to keep Sophia on the stable channel... :-/

**Comment by timothee-haudebourg** [comment]
I'm afraid it wont be avoidable for a little while even if I don't like it either. I need two unstable features: [`generic_associated_types`](https://github.com/rust-lang/rust/issues/44265#issuecomment-923105150) and [`trait_alias`](https://github.com/rust-lang/rust/issues/41517). GAT were supposed to be stabilized soon, I guess there are still some details to figure out. I'm a little bit more worried about trait aliases. Those are required to make the JSON abstraction layer work, but sadly it seems it won't be stabilized soon...

If you really need it and absolutely want to avoid unstable features, I can try to release a `0.4.1` version with those methods, if `crates.io` will let me.

**Comment by timothee-haudebourg** [comment]
I'm currently thinking about [getting rid of the `trait_alias` feature](https://github.com/timothee-haudebourg/json-ld/issues/27). If I can pull that off, then we'll just have to wait until GATs are stabilized (which should happens soon) and `json-ld` will be usable with stable Rust.

**Comment by pchampin** [comment]
Thanks for the feedback. Yes, I would prefer to keep Sophia on the stable channel, but I guess I can wait until GATs are stabilized to further integrate `json-ld`. Anyway, I don't have much time for progressing right now... :-/
