### ISSUE TITLE
Error running the tests from 'master', but can build fine

### ISSUE THREAD

**Issue by tmarkovski** [timothee-haudebourg/json-ld#3]
First of all, thank you for the great work so far on this project. We are looking forward to a JSON-LD 1.1 implementation in Rust for our implementation of [verifiable credentials](https://www.w3.org/TR/vc-data-model/). I know work is still ongoing and wanted to try and play a little bit with the expansion algorithm implemented. I seem to be running into an issue. Using rustup nightly. `cargo build` works fine, but `cargo test` or `cargo run --example generate-expand-tests > tests/expand.rs` results in the below:
Note: this issue isn't anything urgent, I really just wanted to say Hi.

```
Compiling json-ld v0.2.0-alpha (/Users/geddoff/Git/timothee-haudebourg/json-ld)
error[E0478]: lifetime bound not satisfied
  --> examples/custom-ids-iref-enum.rs:32:6
   |
32 |     let context: JsonContext<Id> = JsonContext::new(None);
   |         ^^^^^^^
   |
   = note: lifetime parameter instantiated with any other region
   = note: but lifetime parameter must outlive the static lifetime

error: implementation of `From` is not general enough
   --> examples/generate-expand-tests.rs:100:25
    |
100 |   fn generate_test(entry: &Node<Id>) {
    |                           ^^^^^^^^^ implementation of `From` is not general enough
    | 
   ::: /Users/geddoff/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/convert/mod.rs:373:1
    |
373 | / pub trait From<T>: Sized {
374 | |     /// Performs the conversion.
375 | |     #[lang = "from"]
376 | |     #[stable(feature = "rust1", since = "1.0.0")]
377 | |     fn from(_: T) -> Self;
378 | | }
    | |_- trait `From` defined here
    |
    = note: `From<&'0 Vocab>` would have to be implemented for the type `iref::Iri<'0>`, for any lifetime `'0`...
    = note: ...but `From<&Vocab>` is actually implemented for the type `iref::Iri<'1>`, for some specific lifetime `'1`
```

**Comment by timothee-haudebourg** [comment]
Hi, thanks for the support :smile: 

The master branch is quite far behind now, so I'm not sure to know why it fails... I guess I made a mistake back then, pushing a failing example on the master branch.

It will take a couple of weeks before I can work again actively on this crate, but fixing the examples (in particular this one) so they can work with the more recent API (on the `compaction` branch) is already on my todo list.

In the meantime, if I have time I'll try to publish a fix for this (I think it's just a problem with the version of `iref-enum` that is declared in `Cargo.toml`).

**Comment by timothee-haudebourg** [comment]
I've merged `master` with the `compaction` branch and fixed the examples. You should not have such problems anymore. Note however that I'm currently using a fork of the `json` crate for optimization purposes. i hope I wont have to use it too long, but the `json` crate hasn't been updated in a while...

**Comment by tmarkovski** [comment]
Great, thanks for looking into this @timothee-haudebourg. Nice progress with the compaction algorithm. I believe we can almost implement LD Proofs now, except for the normalization algorithm. Is your plan to reuse an RDF library for the serialization support? `rdf` crate looks fairly feature complete.
