### ISSUE TITLE
Build failure related to AsJson/JsonFrom

### ISSUE THREAD

**Issue by clehner** [timothee-haudebourg/json-ld#33]
When building/testing v0.6.0 (7df142c0adeb24cc9a01fe4e4aae6d3c3a09fd96), I get errors like this:
```
error[E0311]: the associated type `<K as generic_json::Json>::Array` may not live long enough
   --> src/util/json/build.rs:118:53
    |
118 | impl<J: JsonClone, K: JsonFrom<J>, T: AsJson<J, K>> AsJson<J, K> for [T] {
    |                                                     ^^^^^^^^^^^^
    |
    = help: consider adding an explicit lifetime bound `<K as generic_json::Json>::Array: 'a`...
    = note: ...so that the type `<K as generic_json::Json>::Array` will meet its required lifetime bounds...
note: ...that is required by this bound
   --> src/util/json/build.rs:13:35
    |
13  | pub trait AsJson<J: JsonClone, K: JsonFrom<J>> {
    |                                   ^^^^^^^^^^^
```

`cargo 1.60.0-nightly (95bb3c92b 2022-01-18)`

**Comment by timothee-haudebourg** [comment]
That's new... At first glance I would say it is related to https://github.com/rust-lang/rust/issues/87479. I'll investigate.

**Comment by timothee-haudebourg** [comment]
The looks like a compiler bug to me. The lifetime is inconsistently required depending on where the HRTB (comming from the `JsonMut` trait alias used in `JsonFrom`) is placed. I've opened an [issue](https://github.com/rust-lang/rust/issues/93262).

In the meantime, I think I can get around the issue just by removing the `JsonFrom` bound from the `AsJson` trait definition. I hope.
