### ISSUE TITLE
Plans For Normalization Support? Specifically URDNA2015 Normalization

### ISSUE THREAD

**Issue by LuisOsta** [timothee-haudebourg/json-ld#38]
JSON-LD libraries like https://github.com/piprate/json-gold support normalizing JSON-LD documents based on specs like URDNA2015, which is a requirement as part of for instance creating data integrity proofs.

Are there any plans to add normalization support to this library? SpruceID implement it into their identity core library here - https://github.com/spruceid/ssi/blob/main/src/urdna2015.rs

**Comment by timothee-haudebourg** [comment]
Hi, yes this is definitely something that I plan to have eventually. I don't have a timeline yet though, there are a lot of other things I want to finish first.

**Comment by timothee-haudebourg** [comment]
Yes I guess it is out of the scope of this crate.
