### ISSUE TITLE
Stable release channel?

### ISSUE THREAD

**Issue by roper79** [timothee-haudebourg/json-ld#39]
Compiling `0.6.1` with stable `rustc 1.62.1` results in:

```
error[E0554]: `#![feature]` may not be used on the stable release channel
   --> /home/rob/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-traits-0.7.3/src/lib.rs:104:1
    |
104 | #![feature(generic_associated_types)]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Is there a possibility to enable building with stable and avoid nigthtly, which is not endorsed for production?

P.S.
I tried to update the `cc-traits` to the newest `0.8.1`, but the result is the same.

**Comment by timothee-haudebourg** [comment]
Hi, unfortunately generic associated types are required. They are currently in the [process of being stabillized](https://github.com/rust-lang/rust/pull/96709#issuecomment-1181931456) so we just have to wait a little longer.

However we currently also rely on trait aliases, another unstable feature that won't be stabilized any time soon. That is why I'm also working on the new version of `json-ld` that will get rid of all unstable features except for GATs. I'm doing my best to be done as soon as possible to finally have something usable with stable Rust.

**Comment by roper79** [comment]
Thank you very much for your effort and a swift reaction, @timothee-haudebourg! In the meanwhile, I will try to go with nightly.

**Comment by LuisOsta** [comment]
@timothee-haudebourg What is the latest version that works on stable?

**Comment by damooo** [comment]
@timothee-haudebourg , GATS are stabilized now. It will be great if a json-ld parser, transformer is available for rust stable. Thanks for great work.

**Comment by timothee-haudebourg** [comment]
Hey, sorry for the delay I was on break.

Yes GATs are soon to be released on the stable channel (probably with Rust 1.65). But as I said above:

> However we currently also rely on trait aliases, another unstable feature that won't be stabilized any time soon. That is why I'm also working on the new version of json-ld that will get rid of all unstable features except for GATs. I'm doing my best to be done as soon as possible to finally have something usable with stable Rust.

See #37 to see the progress on that. Only some work on the compaction algorithm remains before I can release it.

**Comment by LuisOsta** [comment]
@timothee-haudebourg When do you think we could have a version release of `json-ld` that's stable? Is there anything we can do to help that along

**Comment by timothee-haudebourg** [comment]
If you want a version of `json-ld` that works with Rust stable, I published a [beta version](https://crates.io/crates/json-ld/0.9.1-beta). It still lacks documentation and a few features and design testing before I can release a proper non beta version. If you want to help you can try to use it and give me feedback on the API, although with the current state of the doc, I don't expect it will be easy to do.

Please be patient until I can free some time to finish all that up.

**Comment by roper79** [comment]
Thanks a lot @timothee-haudebourg for your kind effort! That is a great progress, I will definitely give it a try.

**Comment by timothee-haudebourg** [comment]
I've just release version `0.9.1`, which work with stable Rust 1.65. The transition from the old architecture may be rough, please don't hesitate to ask if you need help transitioning.
