### ISSUE TITLE
How to correctly include local context for compaction?

### ISSUE THREAD

**Issue by roper79** [timothee-haudebourg/json-ld#50]
Hi, I am trying to use a local context for compaction. Currently I have:

```
    let context_value = Value::parse_str(context_in_string, |span| span)?;
    let context = RemoteDocumentReference::Loaded(RemoteDocument::new(None, None, context_value));
    let mut loader = json_ld::NoLoader::<IriBuf, Span>::new();
    let compacted = document.compact(context, &mut loader).await;
```
The compiler complains:
```
the trait `From<json_ld::json_ld_syntax::context::Value<locspan::Span>>` is not implemented for `json_ld::json_ld_syntax::Value<locspan::Span>
```

Thanks a lot!

**Comment by timothee-haudebourg** [comment]
Hey, so the compiler error message is confusing here, it is a bit disappointing. The `compact` function expects a remote JSON-LD **context** (`json_ld::syntax::context::Value`), not a JSON(-LD) **document** (`json_ld::syntax::Value`). You can get a context value either:   
- by extracting the `@context` entry of your parsed JSON value and calling [`syntax::TryFromJson::try_from_json`](https://docs.rs/json-ld-syntax/0.10.0/json_ld_syntax/trait.TryFromJson.html) on it; or
- by using the [`ExtractContext::extract_context`](https://docs.rs/json-ld/0.10.0/json_ld/trait.ExtractContext.html#tymethod.extract_context) method implemented on your parsed JSON document, that will do exactly the above for you.

I've not tested it, but if you replace the `context_value` definition with the code below it should work:
```rust
use json_ld::ExtractContext;
let context_value = Value::extract_context(Value::parse_str(context_in_string, |span| span)?)?;
```

**Comment by roper79** [comment]
Thanks a lot, @timothee-haudebourg, using your help I made the compiler happy like this:

```
    let context_value = Value::parse_str(context_in_string, |span| span)?;
    let context = Value::extract_context(context_value)?;
    let context_remote = RemoteDocumentReference::Loaded(RemoteDocument::new(None, None, context));
    let mut loader = json_ld::NoLoader::<IriBuf, Span>::new();
    let compacted = document.compact(context_remote, &mut loader).await;
```
