### ISSUE TITLE
Minimal runnable example

### ISSUE THREAD

**Issue by mattcollier** [timothee-haudebourg/json-ld#6]
@timothee-haudebourg Thanks for putting this together!

It took me a bit of work to get the example in the readme working/modernized.  If I did this in a reasonable way I'd be happy to make a PR for updating the readme example with this code.

https://github.com/mattcollier/jsonld-rust-db/blob/main/src/main.rs

**Comment by timothee-haudebourg** [comment]
I have updated all the examples and tests in the latest version. Thanks anyways :smile:
