### ISSUE TITLE
Implement `std::error::Error` for error types

### ISSUE THREAD

**Issue by damooo** [timothee-haudebourg/json-ld#66]
`json_ld` crate has many error types. But they doesn't implement `stf::error::Error` trait. That trait allows easy integration with the ecosystem, like ability to use `anyhow`, or many interfaces that requires the trait or boxed trait object of the trait.

Thanks for great work.

**Comment by timothee-haudebourg** [comment]
I just checked and this has been solved over time. Unless I missed one, all error types should implement `std::error::Error` now.
